<?php

declare(strict_types=1);

use Marko\Database\Exceptions\RepositoryException;

describe('RepositoryException::generatedKeyNotReadable', function (): void {
    it('names PostgreSQL and MariaDB 10.5+ as the servers that read generated keys back', function (): void {
        $exception = RepositoryException::generatedKeyNotReadable('App\Entity\Token', 'id', 'mysql');

        expect($exception->getSuggestion())
            ->toContain('PostgreSQL and MariaDB 10.5+ support')
            ->and($exception->getSuggestion())->toContain('MySQL and MariaDB before 10.5 do not');
    });

    it('suggests setting the key in PHP', function (): void {
        $exception = RepositoryException::generatedKeyNotReadable('App\Entity\Token', 'id', 'mysql');

        expect($exception->getSuggestion())->toContain("Set 'id' in PHP before saving");
    });

    it('keeps the driver name and entity class in the message', function (): void {
        $exception = RepositoryException::generatedKeyNotReadable('App\Entity\Token', 'id', 'mysql');

        expect($exception->getMessage())->toBe(
            "Primary key 'id' of entity 'App\Entity\Token' is generated by the database, "
            . "but the 'mysql' connection cannot read a generated key back",
        );
    });
});
